---
# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
    node: true
    browser: true

extends:
    - 'airbnb-base'

ignorePatterns: 'index.js'

parserOptions:
    ecmaVersion: latest

rules:
    import/extensions: 0
    import/no-unresolved: 0
    no-param-reassign: 0
    no-console: 0
